apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtrack-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dtrack-apiserver
  template:
    metadata:
      labels:
        app: dtrack-apiserver
    spec:
      containers:
        - name: dtrack-apiserver
          image: dependencytrack/apiserver
          resources:
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: dependency-track
              mountPath: /data
      volumes:
        - name: dependency-track
          emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtrack-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dtrack-frontend
  template:
    metadata:
      labels:
        app: dtrack-frontend
    spec:
      containers:
        - name: dtrack-frontend
          image: dependencytrack/frontend
          env:
            - name: API_BASE_URL
              value: "http://dtrack-apiserver:8080"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service

metadata:
  name: dtrack-apiserver
spec:
  type: NodePort
  selector:
    app: dtrack-apiserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100

---
apiVersion: v1
kind: Service

metadata:
  name: dtrack-frontend
spec:
  type: NodePort
  selector:
    app: dtrack-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
