apiVersion: batch/v1
kind: Job
metadata:
  name: sbom-job
spec:
  template:
    spec:
      restartPolicy: Never

      volumes:
      - name: shared-data
        emptyDir: {}
      initContainers:
      - name: git-container
        image: alpine/git:2.40.1
        volumeMounts:
        - name: shared-data
          mountPath: /pod-data
        resources:
          limits:
            memory: "1Gi"
        command: ["/bin/sh"]
        args: ["-c", "git clone https://github.com/0c34/govwa /pod-data/rep"] # https://github.com/0c34/govwa https://github.com/netlify/gocommerce

      - name: sbom-container
        image: cyclonedx/cyclonedx-gomod
        volumeMounts:
        - name: shared-data
          mountPath: /pod-data
        resources:
          limits:
            memory: "4Gi"
        command: ["/bin/sh"]
        args: ["-c", "cyclonedx-gomod app -output /pod-data/sbom.xml /pod-data/rep && echo 'success'"]

      containers:
      - name: logs
        image: axidex/py
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: my-api-secret
              key: api-key
        - name: IP_DT
          valueFrom:
            configMapKeyRef:
              name: cfg
              key: dtip
        - name: BRANCH_DT
          valueFrom:
            configMapKeyRef:
              name: cfg
              key: branch
        - name: NAME_DT
          valueFrom:
            configMapKeyRef:
              name: cfg
              key: name
        volumeMounts:
        - name: shared-data
          mountPath: /pod-data
        resources:
          limits:
            memory: "2Gi"
        command: ["/bin/sh"]
        args: ["-c", "python3 logger.py $ "]
  backoffLimit: 1 # Число попыток выполнения Job в случае неудачи
