apiVersion: v1
kind: Pod
metadata:
  name: SBOM
spec:

  restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: git-container
    image: alpine/git:2.40.1
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "git clone https://github.com/0c34/govwa /pod-data/rep"]

  - name: sbom-container
    image: cyclonedx/cyclonedx-gomod
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "cyclonedx-gomod app -output /pod-data/sbom.xml /pod-data/rep"]

  - name: logs
    image: axidex/pubuntu
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"] 
    args: ["-c", "curl -v -X "POST" "dependency-track:8080/api/v1/bom" -H "X-API-Key: TimbOxMatBj7kSlCEq9KYJUoY70AsWmK" -H "Content-Type: multipart/form-data" -F "autoCreate=true" -F "projectName=tmp" -F "projectVersion=0.1" -F "bom=@pod-data/sbom.xml" && \
            ec" ] 

  